module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        overlay: "var(--overlay)",
        red: "var(--red)",
        timberwolf: "var(--timberwolf)",
        white: "var(--white)",
        "x-100": "var(--x-100)",
        "x-200": "var(--x-200)",
        "x-300": "var(--x-300)",
        "x-400": "var(--x-400)",
        "x-500": "var(--x-500)",
        "x-600": "var(--x-600)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "display-100": "var(--display-100-font-family)",
        "display-100-demi": "var(--display-100-demi-font-family)",
        "display-100-strikethrough":
          "var(--display-100-strikethrough-font-family)",
        "display-200": "var(--display-200-font-family)",
        "display-300": "var(--display-300-font-family)",
        "display-400": "var(--display-400-font-family)",
        "display-400-demi": "var(--display-400-demi-font-family)",
        "display-500": "var(--display-500-font-family)",
        "display-600-demi": "var(--display-600-demi-font-family)",
        "display-700-dmei": "var(--display-700-dmei-font-family)",
        "display-800": "var(--display-800-font-family)",
        "display-900-demi": "var(--display-900-demi-font-family)",
        "text-100": "var(--text-100-font-family)",
        "text-100-demi": "var(--text-100-demi-font-family)",
        "text-200": "var(--text-200-font-family)",
        "text-200-demi": "var(--text-200-demi-font-family)",
        "text-200-strikethrough": "var(--text-200-strikethrough-font-family)",
        "text-200-underline": "var(--text-200-underline-font-family)",
        "text-300": "var(--text-300-font-family)",
        "text-300-demi": "var(--text-300-demi-font-family)",
        "text-300-underline": "var(--text-300-underline-font-family)",
        "text-400": "var(--text-400-font-family)",
        "text-400-demi": "var(--text-400-demi-font-family)",
        "text-400-underline": "var(--text-400-underline-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      boxShadow: { cart: "var(--cart)" },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [],
  darkMode: ["class"],
};
